feat: reorganize set-env-vars step to use python script
saritasa-nest/saritasa-devops-tekton pull request #11
Opened 2021-09-22 10:14 UTC by kseniyashaydurova

2021-09-22 10:23 UTC, kseniyashaydurova commented
@dmitry-mightydevops Current solution works, but I suggest to make a python script, which will take `source_path` and `env_dir` arguments, so we would call it from linux terminal. So we will have no code repeat and we would be able to use our common approach for `slack error notification` (but to make it work we will need to use centos image instead of alpine)

2021-09-23 04:22 UTC, dmitry-mightydevops commented
> @dmitry-mightydevops Current solution works, but I suggest to make a python script, which will take `source_path` and `env_dir` arguments, so we would call it from linux terminal. So we will have no code repeat and we would be able to use our common approach for `slack error notification` (but to make it work we will need to use centos image instead of alpine)

Not sure I understand - can you elaborate on it more?

2021-09-23 04:28 UTC, dmitry-mightydevops requested changes

2021-09-23 04:28 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/buildpack-task.yaml
> +        ]
We don't need it - as new env vars can appear in all the buildpacks. I did it this way to separate from in-POD env vars. You don't need it as you need to take project.toml as the only source of truth. So whatever the env vars are defined in **project.toml** - you persist them on disk.

2021-09-23 04:28 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/buildpack-task.yaml
> +            parsed = toml.load(f)
let's replace var `parsed` with `settings` as it's more semantic.

2021-09-23 04:28 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/buildpack-task.yaml
> +          raise Exception("Toml file couldn't be parsed\nTraceback: {e}")
Unable to parse project.toml file.

2021-09-23 04:28 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/buildpack-task.yaml
> +          if re.match(regex, name):
no need to match by regexp. See comments above.

2021-09-23 04:28 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/buildpack-task.yaml
> +          if re.match(regex, name):
let's apply the same changes to others below.

2021-09-24 04:17 UTC, dmitry-mightydevops approved these changes
# Love it!

2021-09-24 04:17 UTC, dmitry-mightydevops commented on tekton-pipelines/base/kustomization.yaml
> +  - tasks/set-env-vars-task.yaml
buildpack-env-vars-task.yaml

2021-09-24 04:18 UTC, dmitry-mightydevops commented
![](https://media4.giphy.com/media/VMO6qeIbr7JRLnLTGw/giphy.gif)

2021-09-24 04:29 UTC, roman-mightydevops approved these changes

2021-09-24 13:43 UTC, populov approved these changes

2021-09-26 06:09 UTC, kseniyashaydurova commented on tekton-pipelines/buildpacks-dotnet/tasks/build.yaml
> +        privileged: true
@populov I haven't created `dotnet` build, so I don't know why it was added. Please discuss it with @dmitry-mightydevops

2021-09-26 06:14 UTC, merged