feat: add sending slack message to thread
saritasa-nest/saritasa-devops-tekton pull request #12
Opened 2021-09-26 06:17 UTC by kseniyashaydurova

2021-09-27 14:09 UTC, SergeyDeminSaritasa approved these changes

2021-09-27 23:47 UTC, dmitry-mightydevops commented
@kseniyashaydurova I know you can get channel ID from the URL in the browser
https://app.slack.com/client/T02T7915W/C028FAE5FN1 -> C028FAE5FN1

2021-09-27 23:58 UTC, dmitry-mightydevops requested changes

2021-09-27 23:58 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +          name: slack-api-token-secret  # used for slack api token (common for all projects)
include info how to obtain that token secret. Keep in mind our repo is open to the world. so it should be instructions, now Link to slack UI

2021-09-27 23:58 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        msg_text = "Tekton CI notifications"
let's change it to `tekton ci` or `tekton-ci`

2021-09-27 23:58 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        msg_text = "Tekton CI notifications"
let's also add the comment - that the name should be exact

2021-09-27 23:58 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        thread_env_file="$(workspaces.source.path)/env/SLACK_THREAD"
use outputs for task instead of env vars.
See docs: https://tekton.dev/docs/pipelines/tasks/#emitting-results

2021-09-27 23:58 UTC, dmitry-mightydevops commented on tekton-pipelines/wordpress/build-pipeline.yaml
> +      workspaces:
no need to define workspace for slack notification task if emitting results works
https://tekton.dev/docs/pipelines/tasks/#emitting-results

2021-09-28 03:03 UTC, roman-mightydevops approved these changes

2021-09-28 08:04 UTC, kseniyashaydurova commented
@dmitry-mightydevops @SergeyDeminSaritasa @roman-mightydevops @DanilaKazakevich @populov @MikhailKorol-saritasa @owlfog Added related to slack integration docs - https://github.com/saritasa-nest/saritasa-devops-docs/blob/main/_infra/slack.md

2021-09-29 01:53 UTC, dmitry-mightydevops commented
> @dmitry-mightydevops @SergeyDeminSaritasa @roman-mightydevops @DanilaKazakevich @populov @MikhailKorol-saritasa @owlfog Added related to slack integration docs - https://github.com/saritasa-nest/saritasa-devops-docs/blob/main/_infra/slack.md

Maybe better into _ci or _tekton folders?

2021-09-29 01:55 UTC, dmitry-mightydevops approved these changes

2021-09-29 01:55 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +    - name: thread
![](https://media2.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif)

2021-09-29 05:45 UTC, merged

2021-10-01 02:39 UTC, populov commented
Awesome!