feat: add slack error notification with traceback
saritasa-nest/saritasa-devops-tekton pull request #15
Opened 2021-10-12 10:02 UTC by kseniyashaydurova

**Add `failure info` and `error traceback` for failed tekton builds.** 

Added new step in slack notification called `get-failed-info`, it doesn't raise any errors, so it shouldn't fail on already existing K8S clusters, which use `saritasa-devops-tekton` repo after tag update. 

But it wouldn't work for your already existing projects out of the box, to make it work you will need to update k8s role `{project}-build-pipeline-role` with new resource `pods/log`, cause otherwise this step won't be able to read logs from a broken tekton pod. You can make it in your project terraform repo or live on cluster (cause Dmitry was going to remove tekton related stuff from terraform codes and move it to another place).

**Related terraform PR: https://github.com/saritasa-nest/saritasa-terraform-modules/pull/33**
**Issue: https://github.com/saritasa-nest/saritasa-devops-tekton/issues/10**

**Example of notification with error message:**
![image](https://user-images.githubusercontent.com/26448672/136939304-99527bcd-eada-46d2-bb9b-328c893d03b8.png)

2021-10-13 01:11 UTC, dmitry-mightydevops requested changes

2021-10-13 01:11 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        kubectl -n ci get pipelinerun $pipelinerun_name -o json | jq '[.status.taskRuns | to_entries[] | select ( .value.status.conditions[0].reason == "Failed") | { task: .value.pipelineTaskName, po
pls break it into multiline, so it's easier to see it without horizontal scrolling

2021-10-13 01:11 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        kubectl -n ci get pipelinerun $pipelinerun_name -o json | jq '[.status.taskRuns | to_entries[] | select ( .value.status.conditions[0].reason == "Failed") | { task: .value.pipelineTaskName, po
what happens if permissions are not granted (or overwritten) and this step exits with non zero error code?

2021-10-13 01:11 UTC, dmitry-mightydevops commented on tekton-pipelines/base/tasks/slack-notification-task.yaml
> +        -field6_short false
let's only send this WHEN we got actual error, so we don't have empty sections in "good" slack notification

2021-10-13 03:03 UTC, merged

2021-10-13 03:27 UTC, roman-mightydevops reviewed
Approved

2021-10-18 22:39 UTC, dmitry-mightydevops reviewed
Approved